antonioribeiro/google2fa-laravel

- src/Middleware.php
- src/Support/Auth.php
- src/Support/Authenticator.php
- src/Support/AuthenticatorController.php
- src/Support/Input.php
The Authenticator class is good, but is not very flexible.
This PR splits the Authenticator in 2 classes :
- AuthenticatorController, used by Middleware to handle login request
- Authenticator, which does not depend on the current request, and can be used manually.
Authenticator come with 3 new public functions :
- IsActivated : true if current user has activated 2fa (2fa should be activated/deactivated on demand)
- login : to force login when verification has been made manually in the application (old storeAuthPassed function)
- verifyGoogle2FA($secret, $one_time_password) : to check secret an OTP manually
canPassWithoutCheckingOTP checks if user has activated 2FA (if not, it lets pass without 2FA)
> New authenticator controller

- src/Support/Input.php
the `has` method checks only for key existence and not the value. If the value is empty it's still `true` and leads to an exception.
> fix inputHasOneTimePassword

- src/Support/Authenticator.php
- src/Support/Session.php
For stateless APIs use as follows:
$authenticator = app(Authenticator::class)->boot**Api**($request);
if ($authenticator->isAuthenticated()) {
// otp auth success....
}
> Allow usage of google2FA in stateless APIs

- src/Support/Response.php
The input existence check is already being done within the function checkOTP, this duplication leads to a conflict as the function makeStatusCode returns SymfonyResponse::HTTP_OK when it should return SymfonyResponse::HTTP_UNPROCESSABLE_ENTITY.
> Removed a redundant check

- src/Support/Authenticator.php
- src/Support/Session.php
- tests/Google2FaLaravelTest.php
With the recent session stateless feature, the Google2FA::login() function is not working anymore.
`stateless` property is used in `Session` Trait, and must exist in `Google2FA` class too.
> Fix session stateless usage

- src/Support/ErrorBag.php
- src/config/config.php
This should fix the #60 issue which I've also encountered.
Previously, `config('unknown error')` returned `null`, and then `trans(null)` returned the instance of Laravel Translator, instead of a string. Laravel would then complain with an error similar to `Object of class Illuminate\Translation\FileLoader could not be converted to string`
> Fix the unknown error issue. Closes #60

- src/Google2FA.php
- src/config/config.php
Allow users to use other (svg, eps) image backends for QR code generation.
Fixes #58
> Allow configuring QR image backend

- src/ServiceProvider.php
Closes #73 
There were a couple of issues with the ServiceProvider:
- According to [Laravel documentation](https://laravel.com/docs/5.7/providers#the-register-method) the register method should only used to bind things to the service container. This wasn't the case. Therefore, I moved the `configurePaths` and `mergeConfig` calls to the `boot` method.
- [Deferring a provider](https://laravel.com/docs/5.7/providers#deferred-providers) only works when it only registers to the service container, which isn't the case here. Therefore I removed `$defer = true` and the (now useless) `provides` method.
Currently I have to extend the provider in my own source code to make the config work properly, so I think merging this PR as soon as possible would be very helpful.
> Fix ServiceProvider issues

- src/Support/Authenticator.php
- src/Support/Constants.php
- src/Support/ErrorBag.php
- src/Support/Response.php
- tests/Google2FaLaravelTest.php
Fixes #72 
I added some new constants and used an `HTTP_BAD_REQUEST` to represent an empty OTP submission. The original `checkOTP()` function seemed to be the last check before inputs were passed to the proper Google2FA library for parsing/saving, so I made it a bit more verbose to handle the different conditions. It also assumes a GET request should pass, since credentials are only POSTed for validation.
> Fix issue with OTP form showing an error message on first load

- src/Google2FA.php
I want to propose the following change for, which seems, very exotic reason.
In my environment I share the PHP session with other non-PHP services. This alone is already a challenge due to the native PHP session format (also when e.g. stored in redis) is custom.
Currently this means e.g. NodeJS where I found solution which can de-serialize the session.
However this won't work when "objects" are involved. The unserialize implementations for JavaScript at best can unserialize `stdClass` but they don't know how to handle `\Carbon\Carbon`.
The current code being:
```php
$this->sessionPut(Constants::SESSION_AUTH_TIME, Carbon::now());
```
though stores an actual "object" in the session, complicating matters.
I therefore suggest to simply store the string representation.
To the best of my …
> Use simply string to store in session instead of an object

- src/Support/Authenticator.php
This will fire a `LoginFailed` event when an invalid TOTP code is used.
> fire event for login failed

- README.md
It's already installed as part of the regular dependency:
```
composer.phar require pragmarx/google2fa-laravel
Using version ^1.3 for pragmarx/google2fa-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 6 installs, 1 update, 0 removals
- Installing dasprid/enum (1.0.0): Downloading (100%)
- Installing bacon/bacon-qr-code (2.0.0): Downloading (100%)
- Installing paragonie/constant_time_encoding (v2.3.0): Downloading (100%)
- Installing pragmarx/google2fa (v7.0.0): Downloading (100%)
- Installing pragmarx/google2fa-qrcode (v1.0.3): Downloading (100%)
- Installing pragmarx/google2fa-laravel (v1.3.1): Downloading (100%)
pragmarx/google2fa-laravel suggests installing …
```
> Remove explicit mention of bacon/bacon-qr-code

- README.md
If the OTP lifetime is longer than the Laravel session lifetime, you will be logged out even if your OTP session hasn't expired yet. This PR adds that note to the README.
> Added note for Laravel session lifetime in README

- .travis.yml
- composer.json
- tests/Support/User.php
- Add Support for Laravel 8 (composer version)
- Adapt changed signature of `resolveRouteBinding`
- Improve travis testing matrix to _actually_ test against specific Laravel versions
- composer: all dev dependencies to be installed but prefer stable
> Add explicit support for Laravel 8

- src/config/config.php
Currently the imagemagick plugin does not officially support PHP 8.
For example: Heroku does not support the imagemagick for PHP 8.
> Improve PHP 8 compatibility by not defaulting to imagemagick

- src/Google2FA.php
I'd like to propose the following change to allow updating the window value dynamically.
The following function currently access `$this->config('window')`, and therefore `$this->setWindow()` will not work anymore.
```
public function verifyGoogle2FA($secret, $one_time_password)
{
return $this->verifyKey(
$secret,
$one_time_password,
$this->config('window'),
null, // $timestamp
$this->getOldTimestamp() ?: null
);
}
```
Updating `$this->config('window')` to `$this->getWindow()` will solve this. And the value from config can be set as  default from the boot method.
A use case is explained in #142 
It would be great if this can be merged, please let me know if there's a better way or any changes are required.
Thanks!
@antonioribeiro
> Ability to set window dynamically

- tests/Google2FaLaravelTest.php
Since the default QRcode backend has been changed to SVG, the test testQrcodeInline is failing. Updated test case to check if the output is XML.
> Fix: test case - testQrcodeInline - checking if svg instead of base64

- composer.json
This PR allows the usage of Laravel 9.0 (and phpunit 9.x). 
Fixes: https://github.com/antonioribeiro/google2fa-laravel/issues/162
> Allow upgrade laravel to 9.x and phpunit to 9.x

- README.md
- composer.json
- tests/Google2FaLaravelTest.php
Fixes #181 
- Increased composer.json to allow laravel/framework `>=5.4.36|^8.0|^9.0|^10.0`
- Optionally allowing orchestra/testbench v7 or v8 `3.4.*|3.5.*|3.6.*|3.7.*|4.*|5.*|6.*|7.*|8.*`
- Fixed testLogin to use `session.store` (driver) instead of `session` (manager) - was throwing:
```
1) PragmaRX\Google2FALaravel\Tests\Google2FaLaravelTest::testLogin
TypeError: Illuminate\Session\SymfonySessionDecorator::__construct(): Argument #1 ($store) must be of type Illuminate\Contracts\Session\Session, Illuminate\Session\SessionManager given, called in vendor/laravel/framework/src/Illuminate/Http/Request.php on line 545
```
> Laravel 10.x Support

- composer.json
This enable installs on laravel 6 & 7, the readme says it's supported but the composer.json doesn't include these versions.
> Update Laravel Constraint

- src/Listeners/LoginViaRemember.php
This can fix https://github.com/antonioribeiro/google2fa/issues/169
Just add this in your `App\Providers\EventServiceProvider` class:
```php
use Illuminate\Auth\Events\Login;
use PragmaRX\Google2FALaravel\Listeners\LoginViaRemember;
class EventServiceProvider extends ServiceProvider
{
protected $listen = [
Login::class => [
LoginViaRemember::class,
],
];
...
```
When the session cookie is lost/expired, the `remember` cookie is used, and the `Login` event is triggered. This new listener handles this event to force 2fa login.
> Add a Listener to login via remember

- .github/workflows/run-tests.yml
- .gitignore
- composer.json
- src/Google2FA.php
- This PR already includes https://github.com/antonioribeiro/google2fa-laravel/pull/192
- bump composer verrsions
- needed a fix in `\PragmaRX\Google2FALaravel\Google2FA::minutesSinceLastActivity` due to behaviour change in `Carbon` due to a newer version installed with Laravle 11
- that argument change is backwards compatible, the default of this `$absolute` arg was `true` but changed to `false` in recent releases
- Once merged, I can add a text matrix for supported PHP + Laravel versions (right now, only the PHP version and the matching highest Laravel version, including L11, is tested)
- the successful GHA run can be seen at https://github.com/mfn/google2fa-laravel/actions/runs/8253895412
> Add support for Laravel 11

- README.md
A session in the README file about how one should deal with Laravel login via remember and the 2FA authentication was missing. This PR adds it.
> Add session to readme about 2fa and laravel login via remember

- .github/workflows/run-tests.yml
- composer.json
- Same procedure as every year ;) -> https://github.com/antonioribeiro/google2fa-laravel/pull/196
- Laravel 12 is not released yet, but everything is prepared for it
- adjusted github action to ensure we test the actual PHP & Laravel combinations
- added exclude list for invalid combinations
- Added composer `--no-plugins` because in some older version combinations some dependencies install composer plugins, which would need to be whitelisted etc. -> not worth it
> Add support for Laravel 12
